### ISSUE TITLE
Inkscape 1.3: TexText reports Gio::Error

### ISSUE THREAD

**Issue by quctex** [textext/textext#390] opened 2023-07-24 21:34 UTC
**Steps to reproduce the behavior (if not obvious from description)**:
1. Start Inkscape 1.3 and create new document
2. Run TexText extension 
3. Type `$$1$$` in TexText dialog window
4. Press `Preview` button

**Actual Result**
_Error occurred while generating preview_ window pop-ups

**Expected Result**
Rendered `1` appear in the bottom of TexTex dialog window. 

**Message(s) in error dialog**

<details>
<summary>dialog output</summary>

```
Command C:\Program Files\Inkscape\bin\inkscape.exe --pdf-poppler --pdf-page=1 --export-type=png --export-area-drawing --export-dpi=300 --export-filename tmp.png tmp.pdf failed (code 3)
```
</details>

<details>
<summary>output of stderr:</summary>

```
terminate called after throwing an instance of 'Gio::Error'
```
</details>

**System information**

- TexText version: 1.8.2
- Inkscape version: Inkscape 1.3 (0e150ed6c4, 2023-07-21)
- Operating system: Windows 10, 22H2, 64-bit]
- Windows only: LaTeX-distribution MiKTeX
- Windows only: TexText installed via batch script

**Additional information**

I did not fresh install of Incscape and TexText. When the new version 1.3 came out, I uninstalled the old version 1.2.1 (leaving the profile in %APPDATA%) and installed the new one. The extension was also installed earlier in version 1.2.1. Thus, now version 1.3 works with the old profile from 1.2.1.

**Workaround**
You may have installend Inkscape 1.2.2 with Textext, and unzipped Inkscape 1.3 (from official 7z archive, downloaded from inkscape.org) somewhere another place . 

Since the unzipped Inkscape uses the same settings directory in %APPDATA% as the installed one, the TexText extension will be available to you in version 1.3.

Since the extension was installed for Incscape version 1.2, internally for its work it will run the inkscape.exe v1.2 for its needs.

Thus, you can use the extension while working in version 1.3. Checked.

**Comment by jcwinkler** [comment] 2023-07-25 04:52
Hmm, under Inkscape 1.3 (Windows AND Linux) the TexText dialog does not even show up at all without reporting any errors.

I will mark TexText as uncompatible with Inkscape 1.3.

**Comment by jcwinkler** [comment] 2023-07-25 04:55
@quctex Please could you test the attached package on your system ensuring that only Inkscape 1.3 is used?

[TexText-Windows-1.8.3-dev.zip](https://github.com/textext/textext/files/12157216/TexText-Windows-1.8.3-dev.zip)

Thanks!

**Comment by quctex** [comment] 2023-07-25 05:51
@jcwinkler, are the following steps will be enough to ensure that only Inkscape 1.3 used? 

At the starting point I have 1.2 installed and 1.3 unpacked from 7z.

1. Backup and delete %APPDATA% profile
3. Start and then close 1.3 to make new clear profile
4. Run `setup_win.bat` with `--inkscape-executable` targeted to 1.3 binary.
5. Test textext in 1.3

After that, to revert to my working setup, delete new profile and restore old one from backup.

**Comment by jcwinkler** [comment] 2023-07-25 06:24
Yes, this should be the correct approach.

**Comment by quctex** [comment] 2023-07-25 07:37
Not working:

https://github.com/textext/textext/assets/19704851/eaa1e6e0-df71-4c00-91ee-e8ad37f11214

<details>
  <summary>Confusing backstory</summary>
  I encountered this behavior earlier, after upgrading to 1.3. Since I was running successfully on version 1.3 beta (7z), I didn't expect any trouble updating, and I panicked when *everything* stopped working: all versions, installed and unpacked, beta and stable (I didn't realize then that an extension always uses the Inkscape executable found when the extension is installed, not the one from which the extension is called). I randomly took various actions, sometimes to no avail, sometimes getting various errors. Having achieved nothing, I began to write a bug report from my memory. It was not easy to restore the sequence of events and the environment in order to replicate the behavior of the programs. So I don't think that old report is complete or reliable, so I didn't send it. At one point, the Gio::Error error began to appear and confidently reproduce, and I described it in this new report. Later, if required, I will try to reproduce this error again by installing back 1.3.


Here is that old report that I did not send, considering it not reliable. Keep in mind the fact that at the time of this writing I didn't understand the fact that an TexTex launched from an unpacked Inkscape uses an inkscape.exe executable from another installed Inkscape.


<details>
  <summary>Old Report</summary>
  
**Steps to reproduce the behavior (if not obvious from description)**:
1. Install Inskscape 1.3 and textex extension according [documentation](https://textext.github.io/textext/install/windows.html#textext-on-windows), skipping GtkSourceView step (to avoid its effect), using Setup Script. Get `[TexText][SUCCESS ]: --> TexText has been SUCCESSFULLY installed on your system` message in the end of script execution.
2. Open Inkscape and create new document.
3. Choose main menu `Extentions`->`Text`->`TexText`

**Message(s) in error dialog (if this comes up)**

No messages or error dialogs are comes up.
I don't know how to check if stdout or stderr output are available.

**Logfile**
There is no any *.log file in `C:\Users\[Your user name]\AppData\Roaming\textext`.

**Screenshots**

https://github.com/textext/textext/assets/19704851/6101f309-d308-4ac2-8a3c-335ad5c73a13

**System information**

- TexText version: 1.8.2
- Inkscape version: Inkscape 1.3 (0e150ed6c4, 2023-07-21), Inkscape 1.3-beta (cedbd6c6ff, 2023-05-28)
- Operating system: Windows 10, 22H2, 64-bit
- Windows only: LaTeX-distribution MiKTeX
- Windows only: TexText installed via batch script

**Additional information**

Recently textex is perfectly works for me both in Inkscape 1.2.1 and 1.3-beta installed in parallel as portable app from official beta compressed 7z archive (they are shared same profile settings in %appdata%.

When 1.3 comes out, I did uninstall 1.2.1 and install 1.3. After that, textex began to give an error after pressing the `Preview` button in its GUI:
```
Command C:\Program Files\Inkscape\bin\inkscape.exe --pdf-poppler --pdf-page=1 --export-type=png --export-area-drawing --export-dpi=300 --export-filename tmp.png tmp.pdf failed (code 3)

terminate called after throwing an instance of 'Gio::Error'
```
I reinstalled textext and after that it stopped starting (textext window does not appear), both in Inkscape 1.3 and portable 1.3 beta.

**What was I trying to do**
- Restart Inkscape
- Reboot computer
- Reinstall TexText
- Uninstall and install Inkscape 1.3, using both msi or exe installation packages
- Trying in Inkscape 1.2.2 (from 7z archive)
- Trying in fresh profile (deleting `%appdata%\roaming\inkscape`)
- Remove generic python paths from %PATH% user environment variable, created by python installer from python.org
- remove inkscape itself from %PATH%
  
</details>

And this is error message, throwing by TexText in some steps, that I can't remember, therefore it is not included in the Report:

<details>
  <summary>Ghost error</summary>
 
  
  ```
[TexText][DEBUG   ]: First run of TexText. Enforcing DEBUG mode.
[TexText][DEBUG   ]: TexText initialized
[TexText][DEBUG   ]: TexText version = '1.8.2' (md5sum = 30841cf359fabd5cacc4ba8a123a344e)
[TexText][DEBUG   ]: platform.system() = 'Windows'
[TexText][DEBUG   ]: platform.release() = '10'
[TexText][DEBUG   ]: platform.version() = '10.0.19045'
[TexText][DEBUG   ]: platform.machine() = 'AMD64'
[TexText][DEBUG   ]: platform.uname() = uname_result(system='Windows', node='DESKTOP-49RBBUQ', release='10', version='10.0.19045', machine='AMD64')
[TexText][DEBUG   ]: platform.mac_ver() = ('', ('', '', ''), '')
[TexText][DEBUG   ]: sys.executable = 'C:\\portable\\inkscape-1.2.2_2022-12-09_732a01da63-x64\\bin\\pythonw.exe'
[TexText][DEBUG   ]: sys.version = '3.10.8 (main, Nov  6 2022, 23:27:16)  [GCC 12.2.0 64 bit (AMD64)]'
[TexText][DEBUG   ]: os.environ = environ({'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\Andrey\\AppData\\Roaming', 'COMMANDER_DRIVE': 'C:', 'COMMANDER_EXE': 'C:\\Users\\Andrey\\AppData\\Local\\Programs\\totalcmd\\TOTALCMD64.EXE', 'COMMANDER_INI': 'C:\\Users\\Andrey\\AppData\\Roaming\\GHISLER\\wincmd.ini', 'COMMANDER_INSTANCE': '1', 'COMMANDER_PATH': 'C:\\Users\\Andrey\\AppData\\Local\\Programs\\totalcmd', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'DESKTOP-49RBBUQ', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'DOCUMENT_PATH': '', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\Andrey', 'INKEX_GETTEXT_DIRECTORY': 'C:\\portable\\inkscape-1.2.2_2022-12-09_732a01da63-x64\\share/locale', 'INKEX_GETTEXT_DOMAIN': 'inkscape', 'INKSCAPE_PROFILE_DIR': 'C:\\Users\\Andrey\\AppData\\Roaming\\inkscape', 'LOCALAPPDATA': 'C:\\Users\\Andrey\\AppData\\Local', 'LOGONSERVER': '\\\\DESKTOP-49RBBUQ', 'NUMBER_OF_PROCESSORS': '8', 'ONEDRIVE': 'C:\\Users\\Andrey\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\portable\\inkscape-1.2.2_2022-12-09_732a01da63-x64\\bin;C:\\Program Files\\Inkscape\\bin;C:\\Program Files\\ImageMagick-7.1.0-Q16-HDRI;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\PDFtk Server\\bin\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Common Files\\Autodesk Shared\\;C:\\Program Files\\Common Files\\Autodesk Shared\\Advance\\;C:\\Program Files (x86)\\Common Files\\Autodesk Shared\\Advance\\;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\Users\\Andrey\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Andrey\\AppData\\Local\\Portable\\xpdf-tools-win-4.03\\bin64\\;c:\\Users\\ANDREY\\script\\;c:\\dvsconf\\autocad\\Apps\\fix_pdf_bookmarks\\;c:\\Users\\ANDREY\\AppData\\Local\\portable\\;C:\\Users\\Andrey\\AppData\\Local\\Programs\\MiKTeX\\miktex\\bin\\x64\\;c:\\Users\\ANDREY\\AppData\\Local\\Programs\\KopiaUI\\resources\\server\\;c:\\Users\\ANDREY\\AppData\\Local\\Portable\\micro\\;C:\\Program Files\\Inkscape\\bin;;C:\\portable\\inkscape-1.2.2_2022-12-09_732a01da63-x64\\bin\\', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'AMD64 Family 23 Model 104 Stepping 1, AuthenticAMD', 'PROCESSOR_LEVEL': '23', 'PROCESSOR_REVISION': '6801', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'PYTHONIOENCODING': 'UTF-8', 'PYTHONPATH': 'C:\\Users\\Andrey\\AppData\\Roaming\\inkscape\\extensions;C:\\portable\\inkscape-1.2.2_2022-12-09_732a01da63-x64\\share\\inkscape\\extensions;C:\\portable\\inkscape-1.2.2_2022-12-09_732a01da63-x64\\share\\inkscape\\extensions\\inkex\\deprecated-simple', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\Windows', 'TEMP': 'C:\\Users\\Andrey\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\Andrey\\AppData\\Local\\Temp', 'USERDOMAIN': 'DESKTOP-49RBBUQ', 'USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-49RBBUQ', 'USERNAME': 'Andrey', 'USERPROFILE': 'C:\\Users\\Andrey', 'WINDIR': 'C:\\Windows', 'XDG_DATA_DIRS': 'C:\\ProgramData;C:\\Users\\Public\\Documents;C:\\portable\\inkscape-1.2.2_2022-12-09_732a01da63-x64\\share;C:\\portable\\inkscape-1.2.2_2022-12-09_732a01da63-x64\\share;C:\\portable\\inkscape-1.2.2_2022-12-09_732a01da63-x64\\share;C:\\portable\\inkscape-1.2.2_2022-12-09_732a01da63-x64\\share\\inkscape'})
[TexText][ERROR   ]: Command '['C:\\Program Files\\Inkscape\\bin\\inkscape.exe', '--version']' returned non-zero exit status 3.
[TexText][ERROR   ]: Traceback (most recent call last):
  File "C:\Users\Andrey\AppData\Roaming\inkscape\extensions\textext\__main__.py", line 23, in <module>
    effect = TexText()
  File "C:\Users\Andrey\AppData\Roaming\inkscape\extensions\textext\base.py", line 139, in __init__
    if self.requirements_checker.check() == False:
  File "C:\Users\Andrey\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 741, in check
    check_result = textext_requirements.check()
  File "C:\Users\Andrey\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 479, in check
    result = self.criteria()
  File "C:\Users\Andrey\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 469, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "C:\Users\Andrey\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 530, in and_impl
    L = self.check()
  File "C:\Users\Andrey\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 479, in check
    result = self.criteria()
  File "C:\Users\Andrey\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 469, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "C:\Users\Andrey\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 530, in and_impl
    L = self.check()
  File "C:\Users\Andrey\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 479, in check
    result = self.criteria()
  File "C:\Users\Andrey\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 469, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "C:\Users\Andrey\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 625, in find_inkscape_1_0
    stdout, stderr = defaults.call_command([executable, "--version"])
  File "C:\Users\Andrey\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 185, in call_command
    raise subprocess.CalledProcessError(p.returncode, command)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Inkscape\\bin\\inkscape.exe', '--version']' returned non-zero exit status 3.

[TexText][INFO    ]: TexText finished with error, please run extension again
[TexText][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new?template=bug_report.md
  ```
 
</details>
 Sorry for this longread.

</details>

**Comment by sannant** [comment] 2023-07-25 09:41
Same issue for me just after my ubuntu 20.04 did an update.  Following [(the trouble shoothing instruction](https://textext.github.io/textext/usage/troubleshooting.html), the problem can be boiled down to the command 

```
inkscape --pdf-poppler --pdf-page=1 --export-type=svg --export-text-to-path --export-area-drawing --export-filename test.svg test.pdf
```
Giving the error
```
terminate called after throwing an instance of 'Gio::Error'
Aborted
```

Probably the problem is in inkscape's behavior having changed.

**Comment by jcwinkler** [comment] 2023-07-25 12:35
There are two problems here:

- The call to `inkscape --pdf-poppler ...` has been changed in Inkscape 1.3 This is already addressed in the develop branch of TexText (`pages=1`needs to passed instead of `pdf-pages=1`)
- The `Gio::Error`: This is coming from the gobject retroinspection, the api to the GTK GUI framework. Unfortunately it is not very descriptive and is ONLY thrown when TexText is called from Inkscape. If I invoke TexText from the debugger everything works flawlessly. Currently I try to investigate this in more detail.

**Comment by quctex** [comment] 2023-07-25 12:48
with `pages=1` instead of `pdf-pages=1`:
```
c:\portable\inkscape-1.3_2023-07-21_0e150ed6c4-x64\bin\inkscapecom.com --pdf-poppler pages=1 --export-type=svg --export-text-to-path --export-area-drawing --export-filename test.svg test.pdf

ConcreteInkscapeApplication<Gtk::Application>::on_open: Can't use '--export-filename' with multiple input files (output file would be overwritten for each input file). Please use '--export-type' instead and rename manually.
```

**Comment by jcwinkler** [comment] 2023-07-25 13:02
I am unable to reproduce this on my system...

**Comment by quctex** [comment] 2023-07-25 13:17
my mistake sorry. Missing `--` before `pages=1`. Now it ok:
```
c:\portable\inkscape-1.3_2023-07-21_0e150ed6c4-x64\bin\inkscapecom.com --pdf-poppler --pages=1 --export-type=svg --export-text-to-path --export-area-drawing test.pdf
```

But resulting file is `test.pdf.svg`. The resembling bug is [filed](https://gitlab.com/inkscape/inbox/-/issues/8679).

**Comment by jcwinkler** [comment] 2023-07-25 13:21
@sannant 

> I expected that installing the develop branch of textext will fix the problem.

Yes, this was the case weeks ago. Now we additionally have the GIO problem...

**Comment by quctex** [comment] 2023-07-25 13:26
> But resulting file is `test.pdf.svg` instead of `test.svg`.

Sorry again please. Wrong command parameters. Now its OK with resulting `test.svg`:

```
inkscape-1.3_2023-07-21_0e150ed6c4-x64\bin\inkscapecom.com --pdf-poppler --pages=1 --export-type=svg --export-text-to-path --export-area-drawing --export-filename test.svg test.pdf
```

**Comment by sannant** [comment] 2023-07-25 13:27
> 



> Yes, this was the case weeks ago. Now we additionally have the GIO problem...


Yes but it might be that the Gio:Error is only instantiated when the call of the commandline fails.

**Comment by jcwinkler** [comment] 2023-07-25 13:34
@sannant The key problem is indeed any commandline call. Even when TextText just calls `inkscape --version` this GIO error is thrown. But only when the extension is run from Inkscape. Not when debugging it (using exactly the same extension api).

**Comment by jcwinkler** [comment] 2023-07-25 14:04
> and inkscape freezes.

Wait a bit of time until inkscape is free again. Then you will find in the TexText log sth. like this:

```
[2023-07-25 16:02:18,943][ERROR   ]: Traceback (most recent call last):
  File "C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext\__main__.py", line 23, in <module>
    effect = TexText()
  File "C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext\base.py", line 139, in __init__
    if self.requirements_checker.check() == False:
  File "C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 742, in check
    check_result = textext_requirements.check()
  File "C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 480, in check
    result = self.criteria()
  File "C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 470, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 531, in and_impl
    L = self.check()
  File "C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 480, in check
    result = self.criteria()
  File "C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 470, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 531, in and_impl
    L = self.check()
  File "C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 480, in check
    result = self.criteria()
  File "C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 470, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 626, in find_inkscape_1_3
    stdout, stderr = defaults.call_command([executable, "--version"])
  File "C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 185, in call_command
    raise subprocess.CalledProcessError(p.returncode, "{0}, stderr: {1}".format(command, stderr),
subprocess.CalledProcessError: Command '['C:\\Program Files\\Inkscape\\bin\\inkscapecom.com', '--version'], stderr: b"terminate called after throwing an instance of 'Gio::Error'\r\n"' returned non-zero exit status 3.
          //  __main__.py:58   
```

Here the version check fails, but also the pdf -> svg conversion shows the same issue.

Since everything works perfectly from the debugger I guess it is an Inkscape problem. But I need to create a MWE to proove this.

**Comment by jcwinkler** [comment] 2023-07-25 16:11
I think I found a solution how to fix all these issues. +24h until release.

**Comment by sannant** [comment] 2023-07-25 16:32
Thank you a lot

**Comment by jcwinkler** [comment] 2023-07-25 17:25
Hi @sannant Could please try if this development snapshot works:

Windows:
[TexText-Windows-1.8.3-dev2.zip](https://github.com/textext/textext/files/12163942/TexText-Windows-1.8.3-dev2.zip)

Linux:
[TexText-Linux-1.8.3-dev2.zip](https://github.com/textext/textext/files/12163948/TexText-Linux-1.8.3-dev2.zip)

**Comment by quctex** [comment] 2023-07-25 17:55
It worked for me on Windows! Huge thanks to you, @jcwinkler!

**Comment by onatt** [comment] 2023-07-25 17:56
I had exactly the same problem as sannant. The problem seems to be solved on Linux, too.
Tank you very much @jcwinkler!

**Comment by jcwinkler** [comment] 2023-07-25 18:03
Good to hear. I need to do some code cleanup and setup of the ci tests, then I will release it as 1.9.0

**Comment by sannant** [comment] 2023-07-26 06:15
Awesome, works ! 
Thanks a lot !

**Closed** 2023-07-26 09:25 UTC
Labels: bug, Fixed in develop branch
