### ISSUE TITLE
errors in both linux and windows for inkscape 0.92.3

### ISSUE THREAD

**Issue by habroland** [textext/textext#51] opened 2018-10-22 23:57 UTC
I'm trying to compile $\alpha$. Moreover, for some reason the boxes "Reset" and Alignment are greyed out.
Errors:

In win10 x64:

Your LaTeX code has problems:

Traceback (most recent call last):
  File "asktext.py", line 599, in cb_ok
    self._texcmd_cbox.get_active_text().lower())
  File "textext.py", line 292, in callback
    tex_cmd, original_scale=current_scale)
  File "textext.py", line 393, in do_convert
    new_svg_ele = converter.convert(text, preamble_file, scale_factor, tex_command)
  File "textext.py", line 820, in convert
    self.tex_to_pdf(tex_command, latex_text, preamble_file)
  File "textext.py", line 763, in tex_to_pdf
    raise RuntimeError("Your LaTeX code has problems:\n\n{errors}".format(errors=parsed_log))
RuntimeError: Your LaTeX code has problems:

I had to install ImageMagick-7.0.8-12-Q16-x64-static.exe because I didn't find the one you mentioned. Still, that should not affect the compilation.

In Lubuntu: Linux 4.15.0-36-generic #39-Ubuntu

Command pdflatex /tmp/tmpleV1AO/tmp.tex -interaction=nonstopmode -halt-on-error failed: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/rosado/.config/inkscape/extensions/asktext.py", line 599, in cb_ok
    self._texcmd_cbox.get_active_text().lower())
  File "textext.py", line 292, in callback
    tex_cmd, original_scale=current_scale)
  File "textext.py", line 393, in do_convert
    new_svg_ele = converter.convert(text, preamble_file, scale_factor, tex_command)
  File "textext.py", line 820, in convert
    self.tex_to_pdf(tex_command, latex_text, preamble_file)
  File "textext.py", line 766, in tex_to_pdf
    raise RuntimeError(latest_message())
RuntimeError: Command pdflatex /tmp/tmpleV1AO/tmp.tex -interaction=nonstopmode -halt-on-error failed: [Errno 2] No such file or directory

(textext.py:1490): GLib-GIO-CRITICAL **: 15:42:53.669: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(textext.py:1490): GLib-GIO-CRITICAL **: 15:42:53.670: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

**Comment by sizmailov** [comment] 2018-10-23 10:11
1) Buttons are for re-editing, so they are disabled at first, see issue #25
2) Can't comment on issue on Windows
3) Linux issue seems to be related to #43, please check given solution

**Comment by habroland** [comment] 2018-10-23 21:43
Got the solution for linux:

pdflatex is not installed by default in lubuntu. I got mislead by the "TeX command" box since I thought it would be clever enough to check that the commands are installed before adding them to the drop-down list.
After installing pdflatex, there was another error about the "convert" command of "imagemagick". It was solved by removing some restriction in the policy: https://askubuntu.com/questions/1081895/trouble-with-batch-conversion-of-png-to-pdf-using-convert

I still get the error message about GLib, but I ignore it, since the output is correct.

The error in windows is more obscure. It claims to have an error in the LaTeX code, but the reason (after the colon) is blank. How can I get more insight about this issue?

**Comment by leberwurstsaft** [comment] 2018-10-24 07:45
Regarding the empty error:
The script uses a third party library to parse the tex log to make it more readable and remove the verbosity.
Looks like it either didn’t really find anything to keep, or there was no error after all?
Either way, there should be a check for an empty result of that parser and in that case the whole input error.log should be shown.

**Comment by habroland** [comment] 2018-10-24 18:01
I could not find any error.log file, not sure in which folder it is supposed to be either.
I'm using MikTex 2.9 and made sure all three available TeX commands can be run from the command line
Using TexText in Inkscape, I tried pdflatex and lualatex, both show the same error, while xelatex works fine!

**Comment by jcwinkler** [comment] 2018-10-30 20:58
This is a duplicate of #48. Will continue to investigate this under that issue.

**Closed by jcwinkler** 2018-10-30 20:58 UTC
Labels: duplicate

**Comment by jcwinkler** [comment] 2018-10-31 09:33
> I had to install ImageMagick-7.0.8-12-Q16-x64-static.exe because I didn't find the one you mentioned. Still, that should not affect the compilation.

I updated the links in the WIKI.
