### ISSUE TITLE
TexText 1.0: inkex not found with Inkscape 1.0rc1 (09960d6, 2020-04-09)

### ISSUE THREAD

**Issue by pglpm** [textext/textext#203] opened 2020-04-10 08:40 UTC
I managed to get TexText working with Inkscape 1.0beta2 (5ba348d, 2020-03-28) (but I had to install `lxml` into my machine's python distribution to get that working, as [reported here](https://github.com/textext/textext/issues/202#issue-597620645)).

I tried reinstalling TexText 1.0 with the new Inkscape 1.0rc1 (09960d6, 2020-04-09) – obviously deleting all previous installation files. The install seems successful, but I get this error when I launch TexText:

```
[TexText][ERROR   ]: No module named 'inkex.svg'
[TexText][ERROR   ]: Traceback (most recent call last):
  File "__init__.py", line 584, in <module>
    import inkex.svg
ModuleNotFoundError: No module named 'inkex.svg'

[TexText][INFO    ]: TexText finished with error, please run extension again
[TexText][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new?template=bug_report.md
```

This is strange because the 1.0rc1 *does* include `inkex`. Does this problem come from a wrong configuration of 1.0rc1 itself?

Everything works fine with 1.0beta2 though, so for the moment I'm happily working with that Inkscape version + TexText.

**Logfile**

[textext.log](https://github.com/textext/textext/files/4460638/textext.log)

**System information**

- TexText version: TexText 1.0.0-dev.2 (2020-02-10)
- Inkscape version: Inkscape 1.0rc1 (09960d6, 2020-04-09)
- Operating system: Windows 7 32-bit
- SVG-converter installed (pstoedit+ghostscript or pdf2svg): no idea
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter): probably TkInter
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live): TeX-Live
- Windows only: TexText installed via batch script or installer file: Batch

**Comment by jcwinkler** [comment] 2020-04-10 11:31
OK, thanks for this report. I will check this.

**Comment by jcwinkler** [comment] 2020-04-10 11:34
As a result from your info in #202: If you use your own Python environment on Windows (i.e. not that shipped with inkscpae) your Python path needs to include to the extension subdir of your Inkscape installation so the interpreter finds the inkscape extension api files.

**Comment by pglpm** [comment] 2020-04-10 11:44
I see. Usually I do *not* include my Python distribution in my PATH. So, as part of TexText's setup, should I add Inkscape's python to my  PATH? Or my own distribution + Inkscape's apis? I thought no PATH alteration was necessary – in that case it was a misunderstanding on my part, sorry!

**Comment by sizmailov** [comment] 2020-04-10 11:48
This and #202 sounds like inkscape bug. (You can test it by running other extensions from menu)

**Comment by pglpm** [comment] 2020-04-10 11:49
Indeed, because TexText is working fine with 1.0beta2. I'll report this to Inkscape.

Thank you very much for looking into this!

**Comment by sizmailov** [comment] 2020-04-10 11:51
(Note, `inkex.svg` was recently renamed to `inkex.elements.svg`, so it's not a bug)

**Comment by jcwinkler** [comment] 2020-04-10 19:43
I cannot reproduce the problem with Inkscape RC1 on Windows 10 64bit with the current version of TexText in the develop branch.

In fact this is a duplicate of #194 

Reason is: Our dev2 package does fit to an old state of beta2 but not to the newest one, Note that Windows beta2 packages are nightly builds. 

I will offer an updated TexText package which fits to the most recent beta version of TexText. But at first I have to do some checks with the Linux packages and update the documentation. Tomorrow it will be available.

**Comment by jcwinkler** [comment] 2020-04-10 21:12
@pglpm I provided a new package [dev3](https://github.com/textext/textext/releases/tag/1.0.0-dev.3). Please try! Note the updated [installation instructions](https://textext.github.io/textext/install/windows-beta.html) for Windows.

**Comment by pglpm** [comment] 2020-04-11 09:05
@jcwinkler Thank you very much! Followed the instructions, using the latest Inkscape 1.0rc, and it works like a charm. Now *it also found Inkscape's GTK3*.

I also tried launching Inkscape and then TexText after adding my python distribution in PATH, and everything still works well, no interferences.

Thank you very much for such quick fix! Please feel free to close this issue if you're also happy with it.

**Closed** 2020-04-11 20:16 UTC
Labels: Fixed in develop branch

**Comment by jcwinkler** [comment] 2020-04-28 18:43
@pglpm Since you are working on a 32bit system: If you have the time please could you check the updated installation instructions from https://jcwinkler.github.io/textext/ for Inkscape 1.0 RC1 using the **inkscape exe installer**? Please also try the GtkSourceView approach.

**Comment by pglpm** [comment] 2020-04-29 22:46
Hi, unfortunately my 32-bit laptop died a week ago. I'm using a 64-bit replacement at the moment. If I get the chance I'll try the updated installation instructions on a 32-bit machine and report back here. Sorry about this.

**Comment by jcwinkler** [comment] 2020-04-30 04:49
Thanks!
