### ISSUE TITLE
Weird rendering of font

### ISSUE THREAD

**Issue by owenhdiba** [textext/textext#361] opened 2022-08-25 14:44 UTC
I didn't have any trouble with installation, but the text that is generated by text ext comes out really chunky and odd looking, not at all like in the preview. I also get these warnings:

<frozen importlib._bootstrap>:671: ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()

**Comment by jcwinkler** [comment] 2022-08-25 20:23
@owenhdiba Could give an example please:

- Screenshot
- Latex-Code
- used packages

so I can evaluate what's going on?

> :671: ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()

This message is not related to your observation. It comes from the GTK framework used by some Inkscape extensions (as TexText for example) when their are executed under Python 3.10. Try to open the extension manager in Inkscape and close it. You will see the same message. The problem is discussed [here](https://gitlab.com/inkscape/extensions/-/issues/463)

**Closed** 2022-11-24 08:51 UTC
Labels: Additional info required
