### ISSUE TITLE
Text Appears Vertically Flipped after rendering

### ISSUE THREAD

**Issue by hasantahir** [textext/textext#283] opened 2021-02-12 14:44 UTC
**Description of the problem/ steps to reproduce**
When I use the plugin to render math mode expressions, especially with subscripts and superscripts, the rendered results appear flipped. This only happens when the document is non-empty. In a new or blank document, the text renders fine. 

**Steps to reproduce the behavior (if not obvious from description)**:
1. Create some shapes in the document first
2. Call the extension and write something in the math mode.
3. The rendered text appears vertically flipped (pressing V fixes the orientation). 

**Message(s) in error dialog (if this comes up)**
N/A

**Logfile**
Please also *attach* the TexText log file (since TexText 0.9.x). You find it in `~/.config/inkscape/extensions/textext` on Linux/ MacOS or in `C:\Users\[Your user name]\AppData\Roaming\inkscape\extensions\textext` on Windows

The log file is actually empty (0 B).

**Screenshots**

![lossy-compressed](https://user-images.githubusercontent.com/11236148/107782005-77318280-6d40-11eb-819b-e9d901c8f334.gif)

**System information**

- TexText version: 1.3
- Inkscape version: 1.0
- Operating system: [e.g. Windows 10, 1803, 32-bit] MacOS 11.2.1
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live): MacTeX 2020
- Windows only: TexText installed via batch script or installer file:

**Additional information if you still use Inkscape 0.92.x / TexText 0.11**

- SVG-converter installed (pstoedit+ghostscript or pdf2svg):
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter):

**Comment by jcwinkler** [comment] 2021-02-23 13:58
@hasantahir Excuse me for this very late reply. It is difficult for me to reproduce it since I do not have a MAC system available.

Could you please attach two files

- one which contains minimum content (e.g. a circle and a simple TexText snippet)

- one after you did your modification causing the flipped orientation.

Thanks!

**Comment by hasantahir** [comment] 2021-02-26 11:13
Hi @jcwinkler 

First many thanks for creating such a useful extension that has been immensely helpful. Within the zip, you will find two files as you requested. One more notable thing is the flipped text generated by the extension is outside the page boundaries. In the file attached (`post modification.svg`), I changed the border so that the vertically flipped text is not missed.
Thanks

[Tex Text.zip](https://github.com/textext/textext/files/6049227/Tex.Text.zip)

**Comment by jcwinkler** [comment] 2021-02-26 22:10
OK, thanks @hasantahir I will have a look into the provided files.

**Comment by jcwinkler** [comment] 2021-09-18 06:16
I think this is a duplicate of #313. It will be fixed in release 1.5.1.

**Closed** 2021-10-08 15:13 UTC
Labels: duplicate, Fixed in develop branch

**Comment by jcwinkler** [comment] 2021-10-08 20:41
@hasantahir It should be fixed in release 1.6.0 now.
