### ISSUE TITLE
Error when trying to preview in lualatex.

### ISSUE THREAD

**Issue by charlesd46** [textext/textext#42] opened 2018-09-04 15:42 UTC
Command lualatex c:/users/sec_ch~1/appdata/local/temp/tmpxmfb7u/tmp.tex -interaction=nonstopmode -halt-on-error failed (code 1): This is LuaTeX, Version 1.07.0 (MiKTeX 2.9.6800 64-bit) 
 restricted system commands enabled.
! I can't find file `c:/users/sec_ch'.
<to be read again> 
\protect 
<*> c:/users/sec_ch~
                 1/appdata/local/temp/tmpxmfb7u/tmp.tex -interaction=nonstop...
(Press Enter to retry, or Control-Z to exit)
Please type another input file name: 
! Emergency stop.
<to be read again> 
\protect 
<*> c:/users/sec_ch~
                 1/appdata/local/temp/tmpxmfb7u/tmp.tex -interaction=nonstop...

 236 words of node memory still in use:
   34 glue_spec nodes
   avail lists: 2:12,3:1,4:1,5:1
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on texput.log.

**Comment by jcwinkler** [comment] 2018-09-06 08:09
Unfortunately, I am not able to reproduce the error on my system.

I am a bit puzzled why on the one hand side ```c:/users/sec_ch1``` and on the other hand side ```c:/users/sec_ch~1``` appears in your message (DOS-Windows-path substitution on FAT?).

**Comment by jcwinkler** [comment] 2018-09-07 06:28
OK, this issue is another motivation to implement a debug system as proposed in issue #35 .

**Comment by sizmailov** [comment] 2018-11-30 09:38
@charlesd46 Can you re-paste the error message inside of code block to avoid markdown interpretation.
Use triple back quotes "```" followed by new line to surround error message. 

I would blame this line, specifically the replace:

https://github.com/textext/textext/blob/f174266ab3ea6d5996c264bba198e46803140757/textext.py#L758

**Comment by sizmailov** [comment] 2018-11-30 10:01
In upcoming version we do not use absolute paths to temp files. If my guess is right then issue should be resolved in next release. 

@jcwinkler can you make a premature distribution for tests purpose only? 
@charlesd46 can you try a pre-release version and confirm it.

**Comment by jcwinkler** [comment] 2018-11-30 11:19
I will prepare a premature distro today.

**Closed** 2018-12-20 21:08 UTC
