### ISSUE TITLE
textext gui as a pop-up in focus and keyboard shortcuts

### ISSUE THREAD

**Issue by gerchowl** [textext/textext#370] opened 2022-10-19 08:53 UTC
maybe it is an osx problem. opening the extension always idles inkscape and creates the gui in the background (not in focus) which then needs to be manually chosen and closed. 
Would be awesome if it opens in focus (workaround via cmd+shift+tab is possible) and could be closed with keyboard shortcuts, i.e. cmd+s for save going back to inkscape (as esc or cmd+q can only close without saving option?)

**Comment by jcwinkler** [comment] 2022-10-20 06:12
Thanks for the report!

> and creates the gui in the background (not in focus) which then needs to be manually chosen and closed

I will look into this during the next days.

> and could be closed with keyboard shortcuts

This feature is already available: 
https://textext.github.io/textext/usage/gui.html#selecting-the-shortcut-for-closing-the-textext-window

Does it work under OSX ?

**Comment by gerchowl** [comment] 2022-10-20 07:59
Many thanks.

> This feature is already available: https://textext.github.io/textext/usage/gui.html#selecting-the-shortcut-for-closing-the-textext-window
> 
> Does it work under OSX ?

It works for closing the window, however, only if you would want to close without saving the changes.

The shortcut creates this pop-up.
![Screen Shot 2022-10-20 at 09 07 28](https://user-images.githubusercontent.com/29624937/196890580-b2969a80-c7c2-4386-b1c7-574eaa4d2aed.png)

Confirming with enter drops the changes and goes back to inkscape.

**Comment by jcwinkler** [comment] 2022-10-21 12:29
> Confirming with enter drops the changes and goes back to inkscape.

So am I right that after editing and pressing ESC the dialog shown above appears and when you press ENTER the TexText window closes and all changes are lost? I cannot reproduce this behavior on Windows and Linux.

**Closed** 2022-11-24 08:45 UTC
