### ISSUE TITLE
textext makes inkscape 1.3.x line arrow disappear

### ISSUE THREAD

**Issue by erusyd** [textext/textext#411] opened 2023-12-06 07:53 UTC
![Peek 2023-12-06 17-33](https://github.com/textext/textext/assets/1529102/878da06c-e9a5-4c9c-a969-fbe5fae13433)

As you can see, when I input latex formula through textext, line arrow disappears. When I click the line end again, the arrow appears again. This behavior is annoying.

- TexText version: 1.10.1
- Inkscape version: 1.3.2
- Operating system: Linux Mint 21.2, TeX Live 2022/dev/Debian

**Comment by jcwinkler** [comment] 2023-12-07 13:50
Hmm, I work a lot with figures containing arrow lines and TexText, but I never observed this behaviour and actully cannot reproduce it.

Did you close the issue because you found a solution?

**Comment by jcwinkler** [comment] 2023-12-08 06:26
> Cannot reproduce it? Really strange.

Yes, indeed. Could you send me an svg created by you with an arrow inside it, so I can test?

**Comment by erusyd** [comment] 2023-12-08 12:01
![drawing](https://github.com/textext/textext/assets/1529102/5e4addad-514d-4ceb-987e-83a30e6eb783)

**Comment by erusyd** [comment] 2023-12-08 12:03
[linearrow.zip](https://github.com/textext/textext/files/13613688/linearrow.zip)

**Comment by jcwinkler** [comment] 2023-12-08 13:01
My observation is the following:

- If I select the arrow-line and then open TexText, the arrow disappears after TexText processed its content.
- If I **do not** select the arrow-line and then open TexText, everything is as expected after TexText processed its content, i.e. the arrow is kept. Can you confirm this on your system as well?

(The same holds for the built in tex extension)

**Comment by onatt** [comment] 2023-12-09 10:56
I have exactly the same problem, but it seems to be not related to textext or LaTeX at all. I can reproduce the disappearing markers also with some completely unrelated plugins. For instance, rendering a parametric function or a L-System also makes the arrow heads disappear.

However, it is apparently only a display problem. The arrows reappear as soon as you select the corresponding path.

**Comment by erusyd** [comment] 2023-12-09 11:20
@onatt Yes, it's not related to textext, so I've created an issue in the inkscape gitlab repo.
@jcwinkler As you can see from the following gif, I do not select any arrow-line, but when I use the built-in formula extension, all arrows disappear.
![Peek 2023-12-09 19-13](https://github.com/textext/textext/assets/1529102/c2d1fb27-944b-4bd9-bd28-f3894c806571)

**Comment by erusyd** [comment] 2023-12-09 11:25
The arrows are not lost but only temporarily disappear. When I click each arrow-line, the arrow shows up again. I think it's a software rendering/refreshing problem.

**Comment by onatt** [comment] 2023-12-09 11:25
@erusyd
I also created in issue in the gitlab repro a minute ago (https://gitlab.com/inkscape/inbox/-/issues/9666)

**Closed** 2024-04-12 08:25 UTC
