### ISSUE TITLE
Error with textext

### ISSUE THREAD

**Issue by mbg-nimda** [textext/textext#362] opened 2022-08-25 15:48 UTC
After entering the latex formula here:
![textext](https://user-images.githubusercontent.com/16273604/186709093-d9596cbd-be88-4a0f-ab17-31583c54dcba.png)
When pressing "Save" I get no result , and the following warning:
![image](https://user-images.githubusercontent.com/16273604/186710700-4b08cf3b-c7b9-40c3-b6db-1b25a28f4312.png)
I followed all the steps in the troubleshooting section going from test.tex to test.svg to test.png and this works fine without error statements.

**Comment by jcwinkler** [comment] 2022-08-25 20:34
@mbg-nimda We have two things here:

1. **The `ImportWarning` (your second screeshot):** This is not related to TexText and the error you observe. It results from the GTK framework used by some Inkscape extensions (as TexText, for example) when they are are executed under Python 3.10. Try to open the extension manager in Inkscape and close it. You will see the same message. The problem is discussed [here](https://gitlab.com/inkscape/extensions/-/issues/463). I guess the fix is not available in the current release. You can ignore this warning, although it is a bit annoying to see it each time after TexText has been executed.

2. **The invisible output** Please try the following
   a) Open a new and empty Inkscape document
   b) Enter your Latex code via TexText.
   c) When you closed the ImportWarning window press the button `4` which should zoom the window to the content of the document. Do you see the `\sqrt{2}`now?

![grafik](https://user-images.githubusercontent.com/11866252/186763439-806abc5e-debf-470e-96ba-46b8154ffcd8.png)

Please also provide information about your operating system (Name, version) and your Inkscape version. Thank you!

**Comment by mbg-nimda** [comment] 2022-08-26 10:02
On Thu, 25 Aug 2022 at 22:34, Jan Winkler ***@***.***> wrote:

> @mbg-nimda <https://github.com/mbg-nimda> We have two things here:
>

>    1.
>
>    *The ImportWarning (your second screeshot):* This is not related to
>    TexText and the error you observe. It results from the GTK framework used
>    by some Inkscape extensions (as TexText, for example) when they are are
>    executed under Python 3.10. Try to open the extension manager in Inkscape
>    and close it. You will see the same message. The problem is discussed
>    here <https://gitlab.com/inkscape/extensions/-/issues/463>. I guess
>    the fix is not available in the current release. You can ignore this
>    warning, although it is a bit annoying to see it each time after TexText
>    has been executed.
>
> I can live with it :-)

>
>    1.
>
>    *The invisible output* Please try the following
>    a) Open a new and empty Inkscape document
>    b) Enter your Latex code via TexText.
>    c) When you closed the ImportWarning window press the button 4 which
>    should zoom the window to the content of the document. Do you see the
>    \sqrt{2}now?
>
>  Yes, it works fine, the rendering was so small that I didn't notice its
presence.

> Please also provide information about your operating system (Name,
> version) and your Inkscape version. Thank you!
>
 OS:  Windows 10 Home, Ver.: 21H2
 Inkscape: Inkscape 1.2.1 (9c6d41e410, 2022-07-14)

**Comment by jcwinkler** [comment] 2022-08-27 18:02
> Yes, it works fine, the rendering was so small that I didn't notice its
presence.

Glad, to hear this @mbg-nimda . You can always adjust the scale factor to adapt the size of the snippet to your document properties. The selected scale factor will be used in the next new snippet, too. You can also select the snippet and scale it manually with the mouse. You will find the scale factor after this operation when re-opening the node in TexText. Don't forget to lock the aspect ratio before doing this.

The `ImportWarning` message should be gone by today's release of TexText 1.8.2.

**Closed by jcwinkler** 2022-08-27 18:02 UTC
