### ISSUE TITLE
Gtk warning on save

### ISSUE THREAD

**Issue by grahambaker94** [textext/textext#250] opened 2020-08-28 00:54 UTC
**Steps to reproduce the behavior**:
1. Click Extensions -> Text -> Tex Text
2. Enter latex formula
3. Click Save

**Message**

Inkscape has received additional data from the script executed. The script did not return an error, but this may indicate that the results will not be as expected. 
```
(__main__.py:9360): Gtk-WARNING **: 17:45:26.864: dlopen(@executable_path/../Resources/lib/gtk-3.0/3.0.0/immodules/im-quartz.so, 1): image not found

(__main__.py:9360): Gtk-WARNING **: 17:45:26.864: Loading IM context type 'quartz' failed
```

**System information**

- TexText version: 1.1.0
- Inkscape version: 1.0.0
- Operating system: macos catalina 10.15.6

**Comment by jcwinkler** [comment] 2020-08-28 12:43
This is a duplicate of #238.

**Closed** 2020-10-22 14:18 UTC
Labels: duplicate
