### ISSUE TITLE
TexText does not start after MacOS Big Sur installation

### ISSUE THREAD

**Issue by Prototypemax** [textext/textext#276] opened 2021-01-06 18:54 UTC
**Description of the problem/ steps to reproduce**
After MacOS Big Sur installation I was not able to launch TexText from Inkscape anymore. A error box from Inkscape appears and TexText won't open. Before Big Sur Installation everything went really nice.

**Message(s) in error dialog (if this comes up)**
The error says:
"macOS 11 or later required !"
My system runs 11.1 (20C69).

**Logfile**
Please also *attach* the TexText log file (since TexText 0.9.x). You find it in `~/.config/inkscape/extensions/textext` on Linux/ MacOS or in `C:\Users\[Your user name]\AppData\Roaming\inkscape\extensions\textext` on Windows
Unfortunately I can't find the folder.

**Screenshots**
If applicable and helpful, add screenshots to help explain your problem.
![Bildschirmfoto 2021-01-06 um 19 48 47](https://user-images.githubusercontent.com/35840778/103808391-33b86a00-5058-11eb-88a6-2ba9d19cd67f.png)
Text translated: "The called script has passed additional data to Inkscape. No error message was returned by the script, but the result may be unusable."

**System information**

- TexText version: as I cannot find the folder, probably 1.2 oder 1.3. I downloaded it this autumn.
- Inkscape version: 1.0.1
- Operating system: MacOS Big Sur 11.1 (20C69)

**Comment by jcwinkler** [comment] 2021-01-12 08:50
Unfortunately, without the logfile it is very difficult to determine the source of the problem. 

`.config/inkscape/extensions/textext/textext.log` should be in your homedir. Maybe you have to turn on display of hidden files in your file explorer to see it?

I also tried to grep the error message `macOS 11 or later required` and parts of it in TexText and Inkscape source and I did not find anything.

**Comment by mattfack** [comment] 2021-01-13 18:01
You can find the log under `/Users/yourusername/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/textext` where you can see what is the error. In my case it does not find xelatex, lulatex or pdflatex in the path, which is strange since they are there...

**Comment by mattfack** [comment] 2021-01-13 18:54
In my case even with the line

`python3 setup.py --pdflatex-executable=$(which pdflatex) --lualatex-executable=$(which lualatex) --xelatex-executable=$(which xelatex) --skip-requirements-check`

it still fails due to GTK3 missing.

Downgrading to inkscape 1.0.0 did it, however I still get some errors when I write text, namely:

    
    (__main__.py:29922): Gtk-WARNING **: 19:53:43.252: Locale not supported by C library.
    	Using the fallback 'C' locale.    

    (__main__.py:29922): Gtk-WARNING **: 19:53:43.729: dlopen(@executable_path/../Resources/lib/gtk-3.0/3.0.0/immodules/im-quartz.so, 1): image not found    

    (__main__.py:29922): Gtk-WARNING **: 19:53:43.729: Loading IM context type 'quartz' failed

**Comment by Prototypemax** [comment] 2021-01-13 20:31
@mattfack Thank your for your comment! I found the log file as you wrote. I am wondering why its at that different location?

Here is the log file:
[2020-12-03 18:19:08,117][DEBUG   ]: First run of TexText. Enforcing DEBUG mode.          //  base.py:133  
[2020-12-03 18:19:08,117][DEBUG   ]: TexText initialized          //  base.py:142  
[2020-12-03 18:19:08,118][DEBUG   ]: TexText version = '1.3.0' (md5sum = 110c558157a2b3537550f854fa686d85)          //  base.py:144  
[2020-12-03 18:19:08,118][DEBUG   ]: platform.system() = 'Darwin'          //  base.py:147  
[2020-12-03 18:19:08,118][DEBUG   ]: platform.release() = '19.6.0'          //  base.py:148  
[2020-12-03 18:19:08,118][DEBUG   ]: platform.version() = 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64'          //  base.py:149  
[2020-12-03 18:19:08,118][DEBUG   ]: platform.machine() = 'x86_64'          //  base.py:151  
[2020-12-03 18:19:08,118][DEBUG   ]: platform.uname() = uname_result(system='Darwin', node='Maxs-MacBook-Air.local', release='19.6.0', version='Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64', machine='x86_64', processor='i386')          //  base.py:152  
[2020-12-03 18:19:08,175][DEBUG   ]: platform.mac_ver() = ('10.15.7', ('', '', ''), 'x86_64')          //  base.py:153  
[2020-12-03 18:19:08,175][DEBUG   ]: sys.executable = '/Applications/Inkscape.app/Contents/Resources/bin/python3'          //  base.py:155  
[2020-12-03 18:19:08,175][DEBUG   ]: sys.version = '3.8.5 (default, Sep  8 2020, 23:22:39) \n[Clang 11.0.0 (clang-1100.0.33.17)]'          //  base.py:156  
[2020-12-03 18:19:08,175][DEBUG   ]: os.environ = environ({'USER': 'maxbodenstein', 'PATH': '/Applications/Inkscape.app/Contents/MacOS:/Applications/Inkscape.app/Contents/MacOS/../Resources/bin:/usr/bin:/bin:/usr/sbin:/sbin', 'LOGNAME': 'maxbodenstein', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.erA8sj39kk/Listeners', 'HOME': '/Users/maxbodenstein', 'SHELL': '/bin/bash', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x3', 'TMPDIR': '/var/folders/fx/9d_w_nhs69d0xm76qmj5g_sh0000gn/T/', 'XPC_SERVICE_NAME': '0', 'XPC_FLAGS': '0x0', 'XDG_DATA_HOME': '/Users/maxbodenstein/Library/Application Support/org.inkscape.Inkscape/share', 'XDG_DATA_DIRS': '/Applications/Inkscape.app/Contents/MacOS/../Resources/share', 'XDG_CONFIG_HOME': '/Users/maxbodenstein/Library/Application Support/org.inkscape.Inkscape/config', 'XDG_CONFIG_DIRS': '/Applications/Inkscape.app/Contents/MacOS/../Resources/etc/xdg', 'XDG_CACHE_HOME': '/Users/maxbodenstein/Library/Application Support/org.inkscape.Inkscape/cache', 'GTK_EXE_PREFIX': '/Applications/Inkscape.app/Contents/MacOS/../Resources', 'GTK_DATA_PREFIX': '/Applications/Inkscape.app/Contents/MacOS/../Resources', 'GDK_PIXBUF_MODULE_FILE': '/Applications/Inkscape.app/Contents/MacOS/../Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache', 'INKSCAPE_LOCALEDIR': '/Applications/Inkscape.app/Contents/MacOS/../Resources/share/locale', 'FONTCONFIG_PATH': '/Applications/Inkscape.app/Contents/MacOS/../Resources/etc/fonts', 'GIO_MODULE_DIR': '/Applications/Inkscape.app/Contents/MacOS/../Resources/lib/gio/modules', 'GI_TYPELIB_PATH': '/Applications/Inkscape.app/Contents/MacOS/../Resources/lib/girepository-1.0', 'DYLD_LIBRARY_PATH': '/Applications/Inkscape.app/Contents/MacOS/../Resources/lib:/Applications/Inkscape.app/Contents/MacOS/../Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders', 'PYTHONPATH': '/Users/maxbodenstein/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions:/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions:/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/deprecated-simple', 'PYTHONIOENCODING': 'UTF-8', 'INKEX_GETTEXT_DOMAIN': 'inkscape', 'INKEX_GETTEXT_DIRECTORY': '/Applications/Inkscape.app/Contents/MacOS/../Resources/share/locale', 'LC_CTYPE': 'UTF-8'})          //  base.py:157  
[2020-12-03 18:19:08,462][INFO    ]: Using `pdflatex-executable` = `/Library/TeX/texbin/pdflatex`          //  requirements_check.py:588  
[2020-12-03 18:19:08,956][SUCCESS ]: + [Succ] TexText requirements          //  requirements_check.py:690  
[2020-12-03 18:19:08,957][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0          //  requirements_check.py:330  
[2020-12-03 18:19:08,957][SUCCESS ]: |      inkscape=1.0 is found          //  requirements_check.py:330  
[2020-12-03 18:19:08,957][SUCCESS ]: /-and-+ [Succ] Detect *latex          //  requirements_check.py:330  
[2020-12-03 18:19:08,957][SUCCESS ]: |     /--or-* [Succ] pdflatex is found at `/Library/TeX/texbin/pdflatex`          //  requirements_check.py:330  
[2020-12-03 18:19:08,957][INFO    ]: |     /--or-* [Fail] `lualatex` is NOT found in PATH          //  requirements_check.py:330  
[2020-12-03 18:19:08,958][INFO    ]: |     |      Please follow installation instructions at           //  requirements_check.py:330  
[2020-12-03 18:19:08,958][INFO    ]: |     |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-preparation[0m          //  requirements_check.py:330  
[2020-12-03 18:19:08,958][INFO    ]: |     |      If lualatex is installed in custom location, specify it via           //  requirements_check.py:330  
[2020-12-03 18:19:08,958][INFO    ]: |     |             --lualatex-executable=<path-to-lualatex>          //  requirements_check.py:330  
[2020-12-03 18:19:08,958][INFO    ]: |     |      and run setup.py again          //  requirements_check.py:330  
[2020-12-03 18:19:08,958][INFO    ]: |     /--or-* [Fail] `xelatex` is NOT found in PATH          //  requirements_check.py:330  
[2020-12-03 18:19:08,958][INFO    ]: |            Please follow installation instructions at           //  requirements_check.py:330  
[2020-12-03 18:19:08,959][INFO    ]: |                   [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-preparation[0m          //  requirements_check.py:330  
[2020-12-03 18:19:08,959][INFO    ]: |            If xelatex is installed in custom location, specify it via           //  requirements_check.py:330  
[2020-12-03 18:19:08,959][INFO    ]: |                   --xelatex-executable=<path-to-xelatex>          //  requirements_check.py:330  
[2020-12-03 18:19:08,959][INFO    ]: |            and run setup.py again          //  requirements_check.py:330  
[2020-12-03 18:19:08,959][SUCCESS ]: /-and-+ [Succ] Detect GUI library          //  requirements_check.py:330  
[2020-12-03 18:19:08,959][INFO    ]:       /--or-* [Fail] GTK3 is not found          //  requirements_check.py:330  
[2020-12-03 18:19:08,959][INFO    ]:       |      Please follow installation instructions at           //  requirements_check.py:330  
[2020-12-03 18:19:08,960][INFO    ]:       |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-gtk3[0m          //  requirements_check.py:330  
[2020-12-03 18:19:08,960][SUCCESS ]:       /--or-* [Succ] TkInter is found          //  requirements_check.py:330  
[2020-12-03 18:19:09,152][DEBUG   ]: TexText.effect          //  base.py:214  
[2020-12-03 18:19:09,152][DEBUG   ]:   Using default preamble file `default_packages.tex`          //  base.py:258  
[2020-12-03 18:19:09,152][DEBUG   ]:   Run TexText GUI          //  base.py:301  
[2020-12-03 18:19:55,818][DEBUG   ]:     TexText.do_convert          //  base.py:372  
[2020-12-03 18:19:55,818][DEBUG   ]:       args:          //  base.py:373  
[2020-12-03 18:19:55,818][DEBUG   ]:         self = <textext.base.TexText object at 0x7fec9e07a9a0>          //  base.py:375  
[2020-12-03 18:19:55,818][DEBUG   ]:         text = 'Costs\n'          //  base.py:375  
[2020-12-03 18:19:55,818][DEBUG   ]:         preamble_file = 'default_packages.tex'          //  base.py:375  
[2020-12-03 18:19:55,819][DEBUG   ]:         user_scale_factor = 1.3          //  base.py:375  
[2020-12-03 18:19:55,819][DEBUG   ]:         old_svg_ele = None          //  base.py:375  
[2020-12-03 18:19:55,819][DEBUG   ]:         alignment = 'middle center'          //  base.py:375  
[2020-12-03 18:19:55,819][DEBUG   ]:         tex_command = 'pdflatex'          //  base.py:375  
[2020-12-03 18:19:55,819][DEBUG   ]:         original_scale = None          //  base.py:375  
[2020-12-03 18:19:55,820][DEBUG   ]:         Transform = <class 'inkex.transforms.Transform'>          //  base.py:375  
[2020-12-03 18:19:55,820][DEBUG   ]:         tex_executable = '/Library/TeX/texbin/pdflatex'          //  base.py:375  
[2020-12-03 18:19:55,821][DEBUG   ]:       args: done          //  base.py:375  
[2020-12-03 18:19:55,821][DEBUG   ]:       Converting tex to svg          //  base.py:385  
[2020-12-03 18:19:55,824][DEBUG   ]:         Converting .tex to .pdf          //  base.py:537  
[2020-12-03 18:19:56,303][DEBUG   ]:         Converting .tex to .pdf done          //  base.py:567  
[2020-12-03 18:19:56,853][DEBUG   ]:       Converting tex to svg done          //  base.py:390  
[2020-12-03 18:19:56,856][DEBUG   ]:       Adding new node to document          //  base.py:410  
[2020-12-03 18:19:56,873][DEBUG   ]:       Adding new node to document done          //  base.py:431  
[2020-12-03 18:19:56,873][DEBUG   ]:       Saving global settings          //  base.py:445  
[2020-12-03 18:19:56,874][DEBUG   ]:       Saving global settings done          //  base.py:456  
[2020-12-03 18:19:56,874][DEBUG   ]:     TexText.do_convert done          //  base.py:456  
[2020-12-03 18:19:56,874][DEBUG   ]:   Run TexText GUI done          //  base.py:302  
[2020-12-03 18:19:56,874][DEBUG   ]:   Saving global GUI settings          //  base.py:304  
[2020-12-03 18:19:56,875][DEBUG   ]:   Saving global GUI settings done          //  base.py:306  
[2020-12-03 18:19:56,875][DEBUG   ]: TexText.effect done          //  base.py:315

**Comment by mattfack** [comment] 2021-01-14 17:56
You still have 3 Fail messages:

    [2020-12-03 18:19:08,957][INFO ]: | /--or-* [Fail] lualatex is NOT found in PATH // requirements_check.py:330
    [2020-12-03 18:19:08,958][INFO ]: | /--or-* [Fail] xelatex is NOT found in PATH // requirements_check.py:330
    [2020-12-03 18:19:08,959][INFO ]: /--or-* [Fail] GTK3 is not found // requirements_check.py:330

You can avoid the first 2 with the following command line:
    
    python3 setup.py --pdflatex-executable=$(which pdflatex) --lualatex-executable=$(which lualatex) --xelatex-executable=$(which xelatex) --skip-requirements-check

But this won't fix the third problem, which is GTK-related.

**Comment by ProfFan** [comment] 2021-01-15 17:06
The fix is this: https://wiki.inkscape.org/wiki/index.php/Extension_Interpreters#Selecting_a_specific_interpreter_version_.28via_preferences_file.29

Assuming you have Homebrew Python (3.9), just add an entry to this group in the config file: `/Users/proffan/Library/Application Support/org.inkscape.Inkscape/config/inkscape/preferences.xml`

```
  <group
     id="extensions"
     python-interpreter="/usr/local/bin/python3" />
```

And install the `lxml` package:
```
pip3 install lxml
```
make sure that this is done with the Homebrew pip3!

**Comment by mattfack** [comment] 2021-01-16 10:04
Thanks @ProfFan !

Actually your fix doesn't work for me. It might be due to my system specifics (I have a Silicon Apple M1 macbook pro)

Here my steps:

1. completely removed inkscape 1.0.0
2. installed inkscape 1.0.1 with homebrew
3. installed inkscape with the following line `python3 setup.py --pdflatex-executable=$(which pdflatex) --lualatex-executable=$(which lualatex) --xelatex-executable=$(which xelatex) --skip-requirements-check`
4. the config folder in my case is in `/Users/mysuername/.config/inkscape/preferences.xml` and the python path is `/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/bin/`

The problem is always the GTK3 package which won't load due to the problem discussed [here](https://github.com/textext/textext/issues/267)

**Comment by ProfFan** [comment] 2021-01-17 15:21
@mattfack I guess the problem is that you need to use a x86_64 Homebrew? Unless Inkscape is built for ARM arch?

**Comment by ProfFan** [comment] 2021-01-17 15:24
Again with my method you do not need the `--skip-requirements-check` option at all since GTK is properly detected in this case. Plus, please check if you actually edited the file I pointed out, since the `.config` config seems to be inactivated (I have both config files and only the one I listed works.

**Comment by mattfack** [comment] 2021-01-17 17:10
@ProfFan fair point, I'd dig into it. I thought inkscape 1.0.1 was ready for arm arch.

**Comment by sizmailov** [comment] 2021-01-17 19:38
@ProfFan `lxml` should be available in properly installed inskcape-1.0+ (`inkex` module depends on it). You don't need to do that manually. Note that python inerpreter/env variables with inkscape extensions might be different from what you see in regular console.

@mattfack The error you posted in #267 suggest installing `pango` library (google says it can be installed via brew).

**Comment by sizmailov** [comment] 2021-01-17 19:46
The user inkscape folder can be found via  `inkscape --user-data-directory` command. (@jcwinkler we need to add it the 
corresponding section in docs).

**Comment by mattfack** [comment] 2021-01-18 08:09
@sizmailov I have it installed

**Comment by sizmailov** [comment] 2021-01-18 09:16
> 'libpango-1.0.0.dylib' referenced by the typelib: dlopen(libpango-1.0.0.dylib, 9): image not found

> @sizmailov I have it installed

Is the error still the same? Can you locate `.dylib` on your system? Does setting DYLD_LIBRARY_PATH help? Could be something wrong with (system) environment / library installed / arch mismatch between python interpreter and the library / etc. You need to narrow it down to fix. 

(I'm *nix user, not Mac. Should be no much of a difference *most* of the time, but there are some corner cases)

**Comment by mattfack** [comment] 2021-01-20 08:52
Hi @sizmailov I think the main problem is an arch mismatch: inkscape 1.0.1 is not built for apple silicon, while I have homebrew installed as native, not with Rosetta2. So homebrew is working on the new mac arch, while inkscape is not...I set DYLD_LIBRARY_PATH to point to homebrew lib folder, still I am facing the same error. It's like python is not able to find pango.

The error occurring again and again is

    [TexText][INFO    ]:       /--or-* [Fail] GTK3 is not found

just to summarize, these are my specifics
MacBook Pro (13-inch, M1, 2020)
Python 3.9.1
inkscape 1.0.2
textext 1.3.0

**Comment by sizmailov** [comment] 2021-01-20 09:47
Inkscape runs extensions as subprograms (i.e. via `exec`) so inkscape's arch doesn't matter.

The only thing you should care about is the match between python and the libraries it uses. That's why @jcwinkler [asked](https://github.com/textext/textext/issues/267#issuecomment-728204237) to run 

```python
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk
from gi.repository import Gdk, GdkPixbuf
```

As you can see here inkscape nor textext are not involved. 
Once you make it work you should be able to run textext too.

**Comment by mattfack** [comment] 2021-01-20 09:55
I agree!
@Prototypemax is having the same issue as I have...better to follow the discussion on #267

**Comment by mattfack** [comment] 2021-03-01 16:07
After a clean install of inkscape 1.0.2 and textetxt 1.3.0 I am now able to use textext, but:

1. I had to change the python path for the extensions as suggested by @ProfFan (quoted here)
> Assuming you have Homebrew Python (3.9), just add an entry to this group in the config file: `/Users/proffan/Library/Application Support/org.inkscape.Inkscape/config/inkscape/preferences.xml`
> 
> ```
>   <group
>      id="extensions"
>      python-interpreter="/usr/local/bin/python3" />
> ```
> 
> And install the `lxml` package:
> 
> ```
> pip3 install lxml
> ```
2. the gui has some problems (see image)
![Schermata 2021-03-01 alle 17 02 52](https://user-images.githubusercontent.com/18192538/109524146-70c93780-7ab0-11eb-8ba3-fd2e6381645b.png)

**Comment by jcwinkler** [comment] 2021-03-14 10:42
@mattfack I am sorry for the very late reply to your report. Unfortunately neither me nor @sizmailov (the other developer of TexText) have a MacOS system available for testing. So we cannot reproduce the reported issues. 

The steps you needed to get the shown TK interface running imply that the Inkscape extension system seems to be completely broken on your MacOS system. For example the `lxml` package  should be shipped with Inkscape, not TexText. Also the path to the Python interpreter should be set correctly by Inkscape.

Maybe you can post the problem of the missing lxml to the Inkscape developers?

**Comment by mattfack** [comment] 2021-03-15 09:39
I reported that to the inkscape development team, [here](https://gitlab.com/inkscape/extensions/-/issues/344) the thread.

**Comment by oskay** [comment] 2021-03-15 16:53
The `import gi` issue in Inkscape is documented here: https://gitlab.com/inkscape/inkscape/-/issues/1566

**Comment by Prototypemax** [comment] 2021-03-23 13:36
> Thanks @ProfFan !
> 
> Actually your fix doesn't work for me. It might be due to my system specifics (I have a Silicon Apple M1 macbook pro)
> 
> Here my steps:
> 
> 1. completely removed inkscape 1.0.0
> 2. installed inkscape 1.0.1 with homebrew
> 3. installed textext with the following line `python3 setup.py --pdflatex-executable=$(which pdflatex) --lualatex-executable=$(which lualatex) --xelatex-executable=$(which xelatex) --skip-requirements-check`
> 4. the config folder in my case is in `/Users/mysuername/.config/inkscape/preferences.xml` and the python path is `/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/bin/`
> 
> The problem is always the GTK3 package which won't load due to the problem discussed [here](https://github.com/textext/textext/issues/267)

Sorry for late reply, but this fixed the problem for me so far. Thank you!

**Comment by Prototypemax** [comment] 2021-03-23 13:38
> The fix is this: https://wiki.inkscape.org/wiki/index.php/Extension_Interpreters#Selecting_a_specific_interpreter_version_.28via_preferences_file.29
> 
> Assuming you have Homebrew Python (3.9), just add an entry to this group in the config file: `/Users/proffan/Library/Application Support/org.inkscape.Inkscape/config/inkscape/preferences.xml`
> 
> ```
>   <group
>      id="extensions"
>      python-interpreter="/usr/local/bin/python3" />
> ```
> 
> And install the `lxml` package:
> 
> ```
> pip3 install lxml
> ```
> 
> make sure that this is done with the Homebrew pip3!

Sorry for late reply, but performing these steps (after updating hombrew and python to 3.9) helped me to solve the problem. Now Textex is running again.

**Closed** 2021-09-18 06:18 UTC

**Comment by mattfack** [comment] 2021-09-18 08:10
Actually, I am still facing the same old problem.

I have three versions of python on my system: 
1. 2.7.16 apparently needed by OSX (lazy developers not updating stuff :) )
2. 3.8.2 apparently needed by OSX (other developers that do update stuff :) )
3. 3.9.2 installed via homebrew

I am giving the homebrew python as extension to inkscape as suggested above, textext installs with no issues, but then just does not work. 

I get the error

```
TexText][ERROR   ]: g-invoke-error-quark: Could not locate g_option_error_quark: dlopen(libglib-2.0.0.dylib, 9): no suitable image found.  Did find:
	/Applications/Inkscape.app/Contents/Resources/lib/libglib-2.0.0.dylib: mach-o, but wrong architecture
	/Applications/Inkscape.app/Contents/Resources/lib/libglib-2.0.0.dylib: mach-o, but wrong architecture (1)
[TexText][ERROR   ]: Traceback (most recent call last):
  File "/Users/fmatteo/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/textext/__main__.py", line 24, in <module>
    effect.run()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "/Users/fmatteo/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/textext/base.py", line 181, in effect
    from .asktext import AskTextDefault
  File "/Users/fmatteo/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/textext/asktext.py", line 62, in <module>
    from gi.repository import Gtk
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/GLib.py", line 37, in <module>
    from gi import _option as option
  File "/opt/homebrew/lib/python3.9/site-packages/gi/_option.py", line 40, in <module>
    OPTION_CONTEXT_ERROR_QUARK = GLib.quark_to_string(GLib.option_error_quark())
gi._error.GError: g-invoke-error-quark: Could not locate g_option_error_quark: dlopen(libglib-2.0.0.dylib, 9): no suitable image found.  Did find:
	/Applications/Inkscape.app/Contents/Resources/lib/libglib-2.0.0.dylib: mach-o, but wrong architecture
	/Applications/Inkscape.app/Contents/Resources/lib/libglib-2.0.0.dylib: mach-o, but wrong architecture (1)
```

**Comment by jcwinkler** [comment] 2021-09-19 21:02
@mattfack Still this seems to be a problem of the Python distribution used by the Inkscape extension system or the way Inkscape invokes it.

One question: Are you using Inkscape 1.1 ? If so, are you able to invoke the Extension manager (at the bottom of the extension menu). It also uses gtk via gi. Just as a test.

**Comment by mattfack** [comment] 2021-10-06 09:25
thanks @jcwinkler, you are right indeed: Extension manager does not work.
