### ISSUE TITLE
Problem while converting latex to svg.

### ISSUE THREAD

**Issue by Zawarud** [textext/textext#225] opened 2020-05-12 14:58 UTC
**Description of the problem/ steps to reproduce**
if i use textex give me this problem

**Logfile**
`list index out of range`

**Screenshots**
![immagine](https://user-images.githubusercontent.com/53933533/81708325-6da58200-9471-11ea-8cc3-3ce5c9ca4e04.png)
**System information**

- TexText version:   1.0.0
- Inkscape version:   1.0
- Operating system:    Windows 10 64 bit
- SVG-converter installed (pstoedit+ghostscript or pdf2svg):
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter): PyGTK-Sourceview 3.24.11
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live):   MiKTeX-pdfTeX 2.9.7338
- Windows only: TexText installed via batch script or installer file:  setup_win.bat

p.s.
how install for textex the **SVG-converter(pdf2svg)**  ?

**Comment by jcwinkler** [comment] 2020-05-12 18:51
This is a duplicate of #219

**Comment by jcwinkler** [comment] 2020-05-12 19:22
Your LaTeX distro has some missing packages. Since you are on MiKTeX most likely  `mptopdf`.

The list index out of range error is fixed in TexText 1.0.1.

**Closed by jcwinkler** 2020-05-12 19:22 UTC
Labels: duplicate
