### ISSUE TITLE
When I open textext, the following error is reported.  Is it because of  variable type ? 

### ISSUE THREAD

**Issue by feima0011** [textext/textext#23] opened 2018-05-13 02:48 UTC
Traceback (most recent call last):
  File "textext.py", line 1086, in <module>
    effect.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "textext.py", line 205, in effect
    current_scale *= self.uutounit(1, "pt")
TypeError: unsupported operand type(s) for *=: 'NoneType' and 'float'

**Comment by jcwinkler** [comment] 2018-05-13 07:57
This seems to be a duplicate of issue #15. It is already fixed in the release/0.8 branch. For a quick solution I recommend to open your textext.py and changes the one line according to commit c55d578. (The part of the code can be found in the function `def get_old(self):`).

Does this fix your problem?

**Comment by jcwinkler** [comment] 2018-05-13 14:10
I cherry-picked commit c55d578 into the [releases/0.7 branch](https://github.com/textext/textext/tree/releases/0.7).

Download link for fixed textext.py to replace installed file from version 0.7.2: [textext.py](https://github.com/textext/textext/blob/releases/0.7/textext.py)

**Comment by jcwinkler** [comment] 2018-05-16 20:38
Fixed in release 0.7.3.

**Closed by jcwinkler** 2018-05-16 20:38 UTC
Labels: duplicate
