### ISSUE TITLE
python setup.py from the git repo fails

### ISSUE THREAD

**Issue by moorepants** [textext/textext#50] opened 2018-10-21 01:50 UTC
The setup.py references a non-existent `extensions` directory. It would be nice if one could `git clone` the repo and then either copy the correct files to the inkscape config directory or even just symlink them. Right now `python setup.py` returns `Installation Failed :(` with no useful information.

**Comment by sizmailov** [comment] 2018-10-21 13:40
I get confused with this. It's duplicate of #28

**Closed** 2018-10-30 20:55 UTC
Labels: duplicate
