### ISSUE TITLE
Windows Portable Apps: Tex Text won't start

### ISSUE THREAD

**Issue by noone-g** [textext/textext#288] opened 2021-03-14 18:44 UTC
I installed it using a script with custom path parameters.
It says "textext is installed successfully."
But, in Inkscape 1.0, I can't start it.
Error message:

[TexText][CRITICAL]: + [Fail] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0
[TexText][SUCCESS ]: |      inkscape=1.0 is found
[TexText][CRITICAL]: /-and-+ [Fail] Detect *latex
[TexText][CRITICAL]: |      Please follow installation instructions at 
[TexText][CRITICAL]: |             [94m[4mhttps://textext.github.io/textext/install/windows.html#windows-install-preparation[0m
[TexText][CRITICAL]: |     /--or-* [Fail] `pdflatex.exe` is NOT found in PATH
[TexText][CRITICAL]: |     |      Please follow installation instructions at 
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/windows.html#windows-install-preparation[0m
[TexText][CRITICAL]: |     |      If pdflatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |     |             --pdflatex-executable=<path-to-pdflatex>
[TexText][CRITICAL]: |     |      and run setup.py again
[TexText][CRITICAL]: |     /--or-* [Fail] `lualatex.exe` is NOT found in PATH
[TexText][CRITICAL]: |     |      Please follow installation instructions at 
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/windows.html#windows-install-preparation[0m
[TexText][CRITICAL]: |     |      If lualatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |     |             --lualatex-executable=<path-to-lualatex>
[TexText][CRITICAL]: |     |      and run setup.py again
[TexText][CRITICAL]: |     /--or-* [Fail] `xelatex.exe` is NOT found in PATH
[TexText][CRITICAL]: |            Please follow installation instructions at 
[TexText][CRITICAL]: |                   [94m[4mhttps://textext.github.io/textext/install/windows.html#windows-install-preparation[0m
[TexText][CRITICAL]: |            If xelatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |                   --xelatex-executable=<path-to-xelatex>
[TexText][CRITICAL]: |            and run setup.py again
[TexText][SUCCESS ]: /-and-+ [Succ] Detect GUI library
[TexText][INFO    ]:       /--or-* [Fail] GTK3 is not found
[TexText][INFO    ]:       |      Please follow installation instructions at 
[TexText][INFO    ]:       |             [94m[4mhttps://textext.github.io/textext/install/windows.html#windows-install-gtk3[0m
[TexText][SUCCESS ]:       /--or-* [Succ] TkInter is found
[TexText][ERROR   ]: TexText requirements are not met. Please follow instructions https://textext.github.io/textext/

**Comment by jcwinkler** [comment] 2021-03-14 19:26
The specification of a custom path for the extension does only make sense if Inkscape itself does look into this directory. This option is only required for special configurations. Usually it should be enough to jsut double click on the provided batch file.

By the way: According to the provided log information no latex installation is found, too.

**Comment by noone-g** [comment] 2021-03-14 20:09
Thanks for the reply.

Based on your comments, I tested the Inkscape settings folder for InkscapePortable (from Portableapps.com).
The portable version has a directory management problem.

I had to put textext plugin to both "InkscapePortable\Data\settings\extensions" and "InkscapePortable\Data\settings\inkscape\extensions".

Portable version reads plugins from "InkscapePortable\Data\settings\extensions" but error logs are redirected to "C:\Portable_Apps_Repository\PortableApps\InkscapePortable\Data\settings\inkscape\extensions"

**Comment by jcwinkler** [comment] 2021-03-15 10:14
@noone-g I would like to update the documentation with respect to this topic. It would be very helpful if you could post a short step by step procedure how you did manager to run TexText in that environment (steps, commands, ...). Thanks!

**Comment by noone-g** [comment] 2021-03-16 00:33
Here's what I did to make Tex Text working with the portable Inkscape 1.0.2 (from PortableApps.com):

1. setup_win --inkscape-executable "portable\inkscape\path\to\executable\inkscape.exe" --inkscape-extensions-path "portable\inkscape\data\folder\settings\extensions" --pdflatex-executable "portable\miktex\executale\folder\pdflatex.exe"

2. For the portable Inkscape from PortableApps.com, there is another extensions folder in data/settings/inkscape. textext folder from the previous step is copied to that folder (settings\extentions)

I think the 2nd step is required due to the folder management error of the portable Inkscape. Someday it will be fixed I think.

**Comment by noone-g** [comment] 2022-01-25 22:46
This method does not work anymore since v1.7.1.

**Comment by jcwinkler** [comment] 2022-01-25 22:51
Am I right that 1.7.0 DOES work? Or which version is the first one that breaks TexText?

**Comment by noone-g** [comment] 2022-01-25 22:53
I updated from 1.3.x.

I didn’t test it before since it was working well and recently found the update.

**Comment by noone-g** [comment] 2022-01-27 01:39
I checked all the releases since v1.3.1 and found that the proposed solution works up to v1.5.0.
Based on the Change logs, I think "New: It is now possible to install TexText system wide for all users" might be the reason although not sure.

**Comment by jcwinkler** [comment] 2022-01-27 16:04
Thanks for this indeep investigation. Indeed, in 1.5 we introduced a change how TexText saves its configuration. We needed that because some user requested the possibility to install TexText globally. In case of PortableApps I gues that `AppData\Roaming` is not accessible or not used and, as a consequence, evertyhing is messed up. I will investigate this and come back to you.

**Comment by noone-g** [comment] 2022-01-27 16:27
Thanks for the reply.

I think that global installation as an option otherwise same as before.
Then, it will work again.

The problem happens since v 1.6.0.

I will stick to v 1.5.0 for now.

**Comment by jcwinkler** [comment] 2022-01-31 21:15
I see what the problem is. The path to inkscape.exe specified during installation is not properly used while converting the produced pdf -> svg. I will fix this.

**Comment by jcwinkler** [comment] 2022-02-01 10:58
Hi @noone-g If you like you can use the attached package for a test, Extract it and run

```dos
setup_win.bat --portable-apps-dir C:\Path\To\Your\PortableAppsInstallation
```

from the extracted package directory. Usually `C:\Path\To\Your\PortableAppsInstallation` is `C:\Users\YourUserName\PortableApps`.

Does setup and TexText work on your system now?

[TexText-Windows-1.8.0-dev.zip](https://github.com/textext/textext/files/7977801/TexText-Windows-1.8.0-dev.zip)

**Comment by noone-g** [comment] 2022-02-01 14:57
Thanks for the update.

Installation went through without error.

But, the same error message as before.

[TexText][INFO    ]: Using `inkscape-executable` = `C:\Portable_Apps_Repository\PortableApps\InkscapePortable\App\Inkscape\bin\inkscape.exe`
[TexText][CRITICAL]: + [Fail] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0
[TexText][SUCCESS ]: |      inkscape=1.1 is found
[TexText][CRITICAL]: /-and-+ [Fail] Detect *latex
[TexText][CRITICAL]: |      Please follow installation instructions at
[TexText][CRITICAL]: |             [94m[4mhttps://textext.github.io/textext/install/windows.html#windows-install-preparation[0m
[TexText][CRITICAL]: |     /--or-* [Fail] `pdflatex.exe` is NOT found in PATH
[TexText][CRITICAL]: |     |      Please follow installation instructions at
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/windows.html#windows-install-preparation[0m
[TexText][CRITICAL]: |     |      If pdflatex is installed in custom location, specify it via
[TexText][CRITICAL]: |     |             --pdflatex-executable=<path-to-pdflatex>
[TexText][CRITICAL]: |     |      and run setup.py again
[TexText][CRITICAL]: |     /--or-* [Fail] `lualatex.exe` is NOT found in PATH
[TexText][CRITICAL]: |     |      Please follow installation instructions at
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/windows.html#windows-install-preparation[0m
[TexText][CRITICAL]: |     |      If lualatex is installed in custom location, specify it via
[TexText][CRITICAL]: |     |             --lualatex-executable=<path-to-lualatex>
[TexText][CRITICAL]: |     |      and run setup.py again
[TexText][CRITICAL]: |     /--or-* [Fail] `xelatex.exe` is NOT found in PATH
[TexText][CRITICAL]: |            Please follow installation instructions at
[TexText][CRITICAL]: |                   [94m[4mhttps://textext.github.io/textext/install/windows.html#windows-install-preparation[0m
[TexText][CRITICAL]: |            If xelatex is installed in custom location, specify it via
[TexText][CRITICAL]: |                   --xelatex-executable=<path-to-xelatex>
[TexText][CRITICAL]: |            and run setup.py again
[TexText][SUCCESS ]: /-and-+ [Succ] Detect GUI library
[TexText][SUCCESS ]:       /--or-* [Succ] GTK3 is found
[TexText][SUCCESS ]:       /--or-* [Succ] TkInter is found
[TexText][ERROR   ]: TexText requirements are not met. Please follow instructions https://textext.github.io/textext/

I investigated “os.environ” and couldn’t find portable miktex directory.
And, the installer “setup_win.bat” looks don’t check ‘pdflatex.exe’.

**Comment by jcwinkler** [comment] 2022-02-01 18:32
...and from which location did you download MiKTeX paf file?

**Comment by noone-g** [comment] 2022-02-01 18:59
I did exactly like that.

setup_win.bat --portable-apps-dir C:\Path\To\Your\PortableAppsInstallation --pdflatex-executable C:\Path\To\Your\PdfLatexExe

And setup_win.bat doesn’t take the second argument --pdflatex-executable C:\Path\To\Your\PdfLatexExe.

It says it can’t find the path.

--pdflatex-executable C:\miktexportable\texmfs\install\miktex\bin\x64

I installed the miktex portable from MiKTeX website.

**Comment by noone-g** [comment] 2022-02-01 19:06
Error message:

C:\Portable_Apps_Repository\PortableApps  found
Trying to detect Python interpreter in Inkscape installation directory...
The system cannot find the path specified.
"C:\Portable_Apps_Repository\PortableApps \InkscapePortable\App\Inkscape\bin\python.exe" found

Trying to run "C:\Portable_Apps_Repository\PortableApps \InkscapePortable\App\Inkscape\bin\python.exe" "Z:\Downloaded\Temp\textext-1.8.0-dev\setup.py" --portable-apps-dir C:\Portable_Apps_Repository\PortableApps --pdflatex-executable C:\Portable_Apps_Repository\PortableApps\1-MikTeXPortable\texmfs\install\miktex\bin\x64\pdflatex.exe...

**Comment by jcwinkler** [comment] 2022-02-01 19:17
Ok, I need to dive a little bit deeper into this issue. I will come back to you the next days.

BTW: The batch file is just a wrapper around the python setup.py file. It determines the path to python.exe in the Python installation shipped with Inkscape and then passes all the command line arguments to the python setup script which does the main work.

**Comment by noone-g** [comment] 2022-02-01 19:18
I found that bat file has a problem.

The following works:

setup_win.bat --pdflatex-executable C:\Portable_Apps_Repository\PortableApps\1-MikTeXPortable\texmfs\install\miktex\bin\x64\pdflatex.exe --portable-apps-dir C:\Portable_Apps_Repository\PortableApps

So, after “--portable-apps-dir”, no arguments are transferred to ‘setup.py’

TexText is working again~!

**Comment by jcwinkler** [comment] 2022-02-01 19:22
Ah, that's good to hear. The order of appearance shouldn't matter, so this is definetely a bug which needs to be fixed by me.

**Comment by jcwinkler** [comment] 2022-02-02 09:52
@noone-g I fixed the mistake in the batch file. Problem was that, `--pdflatex-execuable` IS passed to the python script but the path to inkscape.exe contains an illegal whitespace when additional parameters are passed. You see it here in the error log you passed (before `\InkscapePortable`):

```dos
Trying to run "C:\Portable_Apps_Repository\PortableApps \InkscapePortable\App\Inkscape\bin\python.exe"
```

Please try the attached package, again with the command

```dos
setup_win.bat --portable-apps-dir C:\Path\To\Your\PortableAppsInstallation --pdflatex-executable C:\Path\To\Your\PdfLatexExe
```

I really hope evertyhin runs flawlessly now 🙏 

[TexText-Windows-1.8.0-dev2.zip](https://github.com/textext/textext/files/7985262/TexText-Windows-1.8.0-dev2.zip)

**Comment by noone-g** [comment] 2022-02-02 14:50
Confirmed!

It works like a charm~!

Thanks!!

“setup_win.bat --portable-apps-dir C:\Portable_Apps_Repository\PortableApps --pdflatex-executable C:\Portable_Apps_Repository\PortableApps\1-MikTeXPortable\texmfs\install\miktex\bin\x64\pdflatex.exe --lualatex-executable C:\Portable_Apps_Repository\PortableApps\1-MikTeXPortable\texmfs\install\miktex\bin\x64\lualatex.exe --xelatex-executable C:\Portable_Apps_Repository\PortableApps\1-MikTeXPortable\texmfs\install\miktex\bin\x64\xelatex.exe”

**Comment by jcwinkler** [comment] 2022-02-02 23:13
@noone-g You could do me a favour if you could check the updated documentation:

https://jcwinkler.github.io/textext/install/windows.html

Thanks!

**Comment by noone-g** [comment] 2022-02-03 00:20
Very nice except for one typo

“If you use Inkscape in PortableApps you habe to proceed as follows:”

Best!!

**Closed** 2022-02-03 13:54 UTC
Labels: bug
